### ISSUE TITLE
"netstandard not found or is invalid"

### ISSUE THREAD

**Issue by dsyme** [fsprojects/IfSharp#213]
### Description

`"netstandard.dll not found or is invalid"` is shown 

![image](https://user-images.githubusercontent.com/7204669/55031943-b00ac600-5007-11e9-8295-ee72c780e653.png)

### Steps

On windows (or equivalent on linux)

1. `docker run -v %cd%:/notebooks -p:8888:8888 fsprojects/ifsharp`
2. open `http://localhost:8888/notebooks/FSharp_Jupyter_Notebooks.ipynb`

Expected: no errors

**Comment by cgravill** [comment]
Note there's some overlap with #206 and @rudihorn has an improve situation via #207

That looks like an error with the error highlighting, what platform are you on? 

On Windows I get down to the parallel programming section:

![image](https://user-images.githubusercontent.com/1099725/55033293-bbabbc00-500a-11e9-9c49-cd45b77d3052.png)

**Comment by cgravill** [comment]
I'm then able to make a change and do this:

![image](https://user-images.githubusercontent.com/1099725/55033502-3d9be500-500b-11e9-8bfe-a42681f5b7b4.png)

I guess in .NET Core we should be automatically referencing netstandard? I've not tried the experimental .NET Core setup on Windows - working on other things currently.

**Comment by rudihorn** [comment]
Yeah I have noticed that with #207 it is only an Intellisense/highlighting issue but still works.

**Comment by rudihorn** [comment]
A workaround this could be to have a similar workaround as is done to load `System.Runtime.dll` https://github.com/rudihorn/IfSharp/tree/netstandard. There should be a nicer way of doing this though.

**Comment by cartermp** [comment]
This is just another symptom of the larger problem we're working on solving for FSI on .NET Core. The problem ends up getting deep, as we need to read both facade and implementation assemblies in an interactive process. Implementation assemblies can and will change over time, so you need a separate resolver either in NuGet or the .NET SDK to tell you what implementation assemblies are correct for a given context. Until that is resolved, I wouldn't expect to get further than a hack here.

**Comment by rudihorn** [comment]
@cartermp Might it be worth just determining the currently loaded assemblies and then using those?

**Comment by cgravill** [comment]
Thanks for the caution @cartermp is there an issue we could track around this?

**Comment by dsyme** [comment]
> This is just another symptom of the larger problem we're working on solving for FSI on .NET Core. The problem ends up getting deep, as we need to read both facade and implementation assemblies in an interactive process. Implementation assemblies can and will change over time, so you need a separate resolver either in NuGet or the .NET SDK to tell you what implementation assemblies are correct for a given context. Until that is resolved, I wouldn't expect to get further than a hack here.

We're getting this error on .NET Framework/Mono too, so I don't think it's related.  More likely got to do with locating Facades on Mono.

**Comment by cgravill** [comment]
I think the original issue is resolved via fixes in #218 (which also enables XPlot.plotly and other Paket goodness). Give it a go and re-open if there are issues.

We now default reference netstandard on the netcore build as well. Is there any official guidance if that's the right fix? It seems pragmatically a good idea for compatibility but will silently referencing netstandard bite us later?

**Comment by gusennan** [comment]
Hi, thanks for this project, it's pretty awesome.

I'm running this the first time on Windows 10 via Docker, using the method referenced in the original issue, and still see this:

![image](https://user-images.githubusercontent.com/624632/70857074-447ac880-1eb6-11ea-9481-66ce2251dd86.png)

It looks like the same issue, not sure if this is a regression.

**Comment by cgravill** [comment]
@gusennan glad it's useful.

I think there's something not quite right on the code completion for Mono/.NET Core on non-Windows systems. It needs some digging into more deeply. On the plus side while it used to be a blocking error, at least for me it's a fake error which is annoying but can be ignored until someone gets a chance to look at it.
